//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aviacompany_Amomic
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsUsers
    {
        public int ID_Log { get; set; }
        public int User_ID { get; set; }
        public System.DateTime DateTime_Login { get; set; }
        public Nullable<System.DateTime> DateTime_Exit { get; set; }
        public string WasCrashAndReason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
