//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aviacompany_Amomic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.LogsUsers = new HashSet<LogsUsers>();
        }
    
        public int ID { get; set; }
        public int RoleID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<LogsUsers> LogsUsers { get; set; }
        public virtual Offices Offices { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
